# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Нотатки дилетанта
email: indrekis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Так склалося, що я цікавлюся безліччю речей, але справжнім професіоналом у них так і не став. Однак впорядкувати думки та поділитися ними з друзями та знайомими іноді хочеться.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://indrekis.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  indrekis

# Build settings
# theme: minima
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://fontawesome.com/icons
footer_links:
  - title: Home
    url: /
    icon: fa fa-home

author:
  name: Indrekis
  picture: /images/indrekis_1.jpg
  links:
    - title: GitHub
      url: https://github.com/indrekis
      icon: fab fa-github-square    
    
google_analytics: G-ZCFLVJJ186
search_full_content: true

disqus:
    shortname            : indrekis

comments:
    provider: disqus 
    # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
    disqus:
        shortname            : indrekis
    giscus:
        repo                 : indrekis/indrekis.github.io.comments
        repo_id              : R_kgDOJ22ekg 
        category             : Announcements
        category_id          : DIC_kwDOJ22eks4CXonf
        discussion_term      : pathname
        reactions_enabled    : 1
        theme                : preferred_color_scheme    
    
mathjax:
  enable: true             # MathJax equations, e.g. true, false (default)
  combo: "tex-svg"         # "tex-svg" (default), "tex-mml-chtml", etc.
  tags: "ams"              # "none", "ams" (default), "all"
  
kramdown:
  input: GFM
  # parse_block_html: true

# markdown: CommonMarkGhPages
# markdown: kramdown
